# Generated by Django 4.1.5 on 2023-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New folder', max_length=50)),
                ('previous', models.ForeignKey(on_delete=models.SET(1), to='folder.folder')),
            ],
        ),
    ]
