# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    links:
      - "db:db"

  web:
    build: .
    container_name: file_storage_web
    ports: 
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
